---
- hosts: mysql
  remote_user: root
  tasks:
  - name: Install MySQL server
    package: name=mysql-server update_cache=yes state=present

#  - name: Copy mysql_secure_installation
#    copy: src=mysql_secure_installation.sh dest=/root/

#  - name: Setting the execution flag on mysql_secure_installation
#    file: 
#      path: /root/mysql_secure_installation.sh
#      mode: u+x 

#  - debug: msg="MySQL password is {{ mysql_password }}"

#  - name: Run mysql_secure_installation
#    shell: /root/mysql_secure_installation.sh {{ mysql_password }}

#  - name: Install Python pip
#    package: name=python-pip state=present

  - name: Install Python mysql module
    package: name=python-mysqldb state=present

  - name: Create user for all IP addresses
    mysql_user:
      name: admin
      password: "{{ mysql_password }}"
      host: "%"
      priv: '*.*:ALL'

  - name: Create inventory database
    mysql_db:
      name: inventorydb
      state: present
      login_user: admin
      login_password: "{{ mysql_password }}"

  - name: Enable all interfaces
    lineinfile:
      dest: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: bind-address
      line: "# bind-address"

  - name: Restart mysqld 
    service:
      name: mysql
      state: restarted

  - name: Load data
    script: load-data.sh
    environment:
      MYSQL_ROOT_PASSWORD: "{{ mysql_password }}"
      MYSQL_DATABASE: inventorydb




 
